---
- hosts: all
  become: true
  tasks:
    - name: Add dotdeb php7 repository
      apt_repository: repo='deb http://packages.dotdeb.org jessie all'

    - name: Add dotdeb gpg key
      apt_key: url='https://www.dotdeb.org/dotdeb.gpg' state=present

    - name: Update
      apt: update_cache=yes

    - name: Install base tools (needs dotdeb repo)
      apt: name={{item}} state=present
      with_items:
        - php-fpm
        - php-cli
        - php-mysql
        - php-mbstring
        - php-xml
        - git
        - vim
        - nginx

    - name: Create openssl self-signed certificate
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/test-selfsigned.key -out /etc/ssl/certs/test-selfsigned.crt -subj "/C=BO/ST=BO/L=LP/O=hackaton/OU=hackaton/CN={{ ansible_eth0["ipv4"]["address"] }}"
      run_once: true

    - name: Created Diffie Helman file
      command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/home/ansible/.dh_generated
      run_once: true

    - name: Add laravel nginx config file
      template: src=templates/laravel.conf dest=/etc/nginx/sites-available/default
      notify: restart-nginx

    # https://github.com/Vinelab/ansible-composer/
    - name: download composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer

    - name: install composer
      shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
      args:
        creates: /usr/local/bin/composer

    - name: rename composer.phar to composer
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      args:
        creates: /usr/local/bin/composer

    - name: make composer executable
      file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file

    - name: Clone repo
      git: repo=https://github.com/sguillen-proyectos/test-stob.git dest=/var/www/site

    - name: Install composer dependencies
      composer: working_dir=/var/www/site command=install

  handlers:
    - name: restart-nginx
      service: name=nginx state=restarted
